//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace MC.ControlPedido.Model
{
    public partial class ccb03per
    {
        #region Primitive Properties
    
        public virtual string ccb03emp
        {
            get;
            set;
        }
    
        public virtual string ccb03cod
        {
            get;
            set;
        }
    
        public virtual string ccb03des
        {
            get;
            set;
        }
    
        public virtual bool ccb03proc
        {
            get;
            set;
        }
    
        public virtual bool ccb03conc
        {
            get;
            set;
        }
    
        public virtual Nullable<double> ccb03tc
        {
            get;
            set;
        }
    
        public virtual Nullable<double> ccb03ipm
        {
            get;
            set;
        }
    
        public virtual Nullable<double> ccb03cms
        {
            get;
            set;
        }
    
        public virtual Nullable<double> ccb03cmd
        {
            get;
            set;
        }
    
        public virtual Nullable<double> ccb03fa00
        {
            get;
            set;
        }
    
        public virtual Nullable<double> ccb03fa01
        {
            get;
            set;
        }
    
        public virtual Nullable<double> ccb03fa02
        {
            get;
            set;
        }
    
        public virtual Nullable<double> ccb03fa03
        {
            get;
            set;
        }
    
        public virtual Nullable<double> ccb03fa04
        {
            get;
            set;
        }
    
        public virtual Nullable<double> ccb03fa05
        {
            get;
            set;
        }
    
        public virtual Nullable<double> ccb03fa06
        {
            get;
            set;
        }
    
        public virtual Nullable<double> ccb03fa07
        {
            get;
            set;
        }
    
        public virtual Nullable<double> ccb03fa08
        {
            get;
            set;
        }
    
        public virtual Nullable<double> ccb03fa09
        {
            get;
            set;
        }
    
        public virtual Nullable<double> ccb03fa10
        {
            get;
            set;
        }
    
        public virtual Nullable<double> ccb03fa11
        {
            get;
            set;
        }
    
        public virtual Nullable<double> ccb03fa12
        {
            get;
            set;
        }
    
        public virtual Nullable<double> ccb03FacClose
        {
            get;
            set;
        }
    
        public virtual Nullable<double> ccb03InvClose
        {
            get;
            set;
        }
    
        public virtual string ccb03CtaClose
        {
            get;
            set;
        }

        #endregion
    }
}
