//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace MC.ControlPedido.Model
{
    public partial class In01LinArt
    {
        #region Primitive Properties
    
        public virtual string In01CodEmp
        {
            get;
            set;
        }
    
        public virtual string In01CodLinArt
        {
            get;
            set;
        }
    
        public virtual string in01aa
        {
            get;
            set;
        }
    
        public virtual string In01Descripcion
        {
            get;
            set;
        }

        #endregion
    }
}
