//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace MC.ControlPedido.Model
{
    public partial class in01arti
    {
        #region Primitive Properties
    
        public virtual string IN01CODEMP
        {
            get;
            set;
        }
    
        public virtual string IN01AA
        {
            get;
            set;
        }
    
        public virtual string IN01KEY
        {
            get;
            set;
        }
    
        public virtual string IN01DESLAR
        {
            get;
            set;
        }
    
        public virtual string IN01UNIMED
        {
            get;
            set;
        }
    
        public virtual string IN01UNIDADEQUI
        {
            get;
            set;
        }
    
        public virtual Nullable<double> IN01MONTOEQUI
        {
            get;
            set;
        }
    
        public virtual string IN01CODPRO
        {
            get;
            set;
        }
    
        public virtual string IN01FLAALM
        {
            get;
            set;
        }
    
        public virtual string IN01FLADES
        {
            get;
            set;
        }
    
        public virtual string IN01FLAFAB
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> IN01FECMAT
        {
            get;
            set;
        }
    
        public virtual string IN01CTAINGRESO
        {
            get;
            set;
        }
    
        public virtual string IN01CTAEGRESO
        {
            get;
            set;
        }
    
        public virtual string IN01MOV
        {
            get;
            set;
        }
    
        public virtual string IN01CTAGTO
        {
            get;
            set;
        }
    
        public virtual string IN01CTAING
        {
            get;
            set;
        }
    
        public virtual string In01UnidadMayor
        {
            get;
            set;
        }
    
        public virtual string IN01ESTADO
        {
            get;
            set;
        }
    
        public virtual string IN01TIPO
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> IN01ULTFECING
        {
            get;
            set;
        }
    
        public virtual string IN01NRODEPARTE
        {
            get;
            set;
        }
    
        public virtual string IN01KEYANTERIOR
        {
            get;
            set;
        }
    
        public virtual string IN01CODCONSIGNACION
        {
            get;
            set;
        }
    
        public virtual string in01FlagStockDiario
        {
            get;
            set;
        }

        #endregion
    }
}
