//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace MC.ControlPedido.Model
{
    public partial class In04axal
    {
        #region Primitive Properties
    
        public virtual string IN04CODEMP
        {
            get;
            set;
        }
    
        public virtual string IN04AA
        {
            get;
            set;
        }
    
        public virtual string IN04MM
        {
            get;
            set;
        }
    
        public virtual string IN04KEY
        {
            get;
            set;
        }
    
        public virtual string IN04CODALM
        {
            get;
            set;
        }
    
        public virtual string IN04UBICAC
        {
            get;
            set;
        }
    
        public virtual Nullable<double> IN04STOMIN
        {
            get;
            set;
        }
    
        public virtual Nullable<double> IN04STOSEG
        {
            get;
            set;
        }
    
        public virtual Nullable<double> IN04STOMAX
        {
            get;
            set;
        }
    
        public virtual Nullable<double> IN04STOREP
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> IN04FECINI
        {
            get;
            set;
        }
    
        public virtual Nullable<double> IN04STOCK
        {
            get;
            set;
        }
    
        public virtual Nullable<double> IN04CANTINGRE
        {
            get;
            set;
        }
    
        public virtual Nullable<double> IN04CANTSALID
        {
            get;
            set;
        }
    
        public virtual Nullable<double> IN04IMPINGSOL
        {
            get;
            set;
        }
    
        public virtual Nullable<double> IN04IMPSALSOL
        {
            get;
            set;
        }
    
        public virtual Nullable<double> IN04IMPINGDOL
        {
            get;
            set;
        }
    
        public virtual Nullable<double> IN04IMPSALDOL
        {
            get;
            set;
        }
    
        public virtual Nullable<double> IN04PROMSOL
        {
            get;
            set;
        }
    
        public virtual Nullable<double> IN04PROMDOL
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> IN04FECHAING
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> IN04FECHASAL
        {
            get;
            set;
        }
    
        public virtual Nullable<double> IN04COSTOSOL
        {
            get;
            set;
        }
    
        public virtual Nullable<double> IN04COSTODOL
        {
            get;
            set;
        }
    
        public virtual Nullable<double> IN04ULTCOSSOL
        {
            get;
            set;
        }
    
        public virtual Nullable<double> IN04ULTCOSDOL
        {
            get;
            set;
        }
    
        public virtual Nullable<double> IN04ULTCANING
        {
            get;
            set;
        }
    
        public virtual Nullable<double> IN04ULTCANSAL
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> IN04FEINFI
        {
            get;
            set;
        }
    
        public virtual Nullable<double> IN04STINFI
        {
            get;
            set;
        }
    
        public virtual string IN04TMP
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> IN04STOCKMES
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> IN04STOCKINICIALMES
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> IN04CANTINGINI
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> IN04CANTSALINI
        {
            get;
            set;
        }
    
        public virtual Nullable<double> IN04IMPINGINISOL
        {
            get;
            set;
        }
    
        public virtual Nullable<double> IN04IMPSALINISOL
        {
            get;
            set;
        }
    
        public virtual Nullable<double> IN04IMPINGINIDOL
        {
            get;
            set;
        }
    
        public virtual Nullable<double> IN04IMPSALINIDOL
        {
            get;
            set;
        }
    
        public virtual Nullable<double> IN04PROMINISOL
        {
            get;
            set;
        }
    
        public virtual Nullable<double> IN04PROMINIDOL
        {
            get;
            set;
        }
    
        public virtual string IN04CATEXCONSUMO
        {
            get;
            set;
        }
    
        public virtual string IN04CATEXPRODUCCION
        {
            get;
            set;
        }
    
        public virtual Nullable<double> IN04NIVELDESTOCK
        {
            get;
            set;
        }

        #endregion
    }
}
