//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace MC.ControlPedido.Model
{
    public partial class In09Almacen
    {
        #region Primitive Properties
    
        public virtual string in09codemp
        {
            get;
            set;
        }
    
        public virtual string in09codigo
        {
            get;
            set;
        }
    
        public virtual string in09descripcion
        {
            get;
            set;
        }

        #endregion
    }
}
