//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace MC.ControlPedido.Model
{
    public partial class in23responsable
    {
        #region Primitive Properties
    
        public virtual string in23codemp
        {
            get;
            set;
        }
    
        public virtual string in23Codigo
        {
            get;
            set;
        }
    
        public virtual string In23Descri
        {
            get;
            set;
        }
    
        public virtual string in23tipo
        {
            get;
            set;
        }
    
        public virtual string in23SistemaUsuario
        {
            get;
            set;
        }

        #endregion
    }
}
