//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace MC.ControlPedido.Model
{
    public partial class In60detalleSeg
    {
        #region Primitive Properties
    
        public virtual string In60codemp
        {
            get;
            set;
        }
    
        public virtual string In60aa
        {
            get;
            set;
        }
    
        public virtual string In60numped
        {
            get;
            set;
        }
    
        public virtual string In60Area
        {
            get;
            set;
        }
    
        public virtual int In60Item
        {
            get;
            set;
        }
    
        public virtual int In60NroIntento
        {
            get;
            set;
        }
    
        public virtual Nullable<int> in60FlujoProceso
        {
            get;
            set;
        }
    
        public virtual string In60EstadoAprob
        {
            get;
            set;
        }
    
        public virtual Nullable<double> In60CantidadNueva
        {
            get;
            set;
        }
    
        public virtual string In60Observacion
        {
            get;
            set;
        }
    
        public virtual Nullable<int> in60flagultimoestado
        {
            get;
            set;
        }
    
        public virtual Nullable<int> in60Cerrado
        {
            get;
            set;
        }
    
        public virtual string in60UsuarioMod
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> in60FechaMod
        {
            get;
            set;
        }

        #endregion
    }
}
