//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace MC.ControlPedido.Model
{
    public partial class In60pedido
    {
        #region Primitive Properties
    
        public virtual string In60codemp
        {
            get;
            set;
        }
    
        public virtual string In60aa
        {
            get;
            set;
        }
    
        public virtual string In60cencos
        {
            get;
            set;
        }
    
        public virtual string In60numped
        {
            get;
            set;
        }
    
        public virtual string In60codcli
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> In60fecha
        {
            get;
            set;
        }
    
        public virtual string In60codres
        {
            get;
            set;
        }
    
        public virtual string In60EspTec
        {
            get;
            set;
        }
    
        public virtual string In60Obser
        {
            get;
            set;
        }
    
        public virtual string In60Estado
        {
            get;
            set;
        }
    
        public virtual Nullable<double> In60Aprobado
        {
            get;
            set;
        }
    
        public virtual string In60Expor
        {
            get;
            set;
        }
    
        public virtual string In60Area
        {
            get;
            set;
        }
    
        public virtual string In60DestinoOrigen
        {
            get;
            set;
        }
    
        public virtual string In60TipoPedido
        {
            get;
            set;
        }
    
        public virtual string In60NameUser
        {
            get;
            set;
        }
    
        public virtual string in60mm
        {
            get;
            set;
        }
    
        public virtual string in60tipo
        {
            get;
            set;
        }
    
        public virtual string in60mmProv
        {
            get;
            set;
        }
    
        public virtual string in60aaProv
        {
            get;
            set;
        }
    
        public virtual Nullable<int> in60nivelflujo
        {
            get;
            set;
        }

        #endregion
    }
}
