//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace MC.ControlPedido.Model
{
    public partial class In60detalle
    {
        #region Primitive Properties
    
        public virtual string In60codemp
        {
            get;
            set;
        }
    
        public virtual string In60aa
        {
            get;
            set;
        }
    
        public virtual string In60cencos
        {
            get;
            set;
        }
    
        public virtual string In60numped
        {
            get;
            set;
        }
    
        public virtual string In60codalm
        {
            get;
            set;
        }
    
        public virtual string In60codart
        {
            get;
            set;
        }
    
        public virtual int In60Item
        {
            get;
            set;
        }
    
        public virtual string In60desart
        {
            get;
            set;
        }
    
        public virtual string In60unidad
        {
            get;
            set;
        }
    
        public virtual Nullable<double> In60cantidad
        {
            get;
            set;
        }
    
        public virtual string In60Estado
        {
            get;
            set;
        }
    
        public virtual string In60Area
        {
            get;
            set;
        }
    
        public virtual string In60NameUser
        {
            get;
            set;
        }
    
        public virtual string In60NroParte
        {
            get;
            set;
        }
    
        public virtual string In60Prioridad
        {
            get;
            set;
        }
    
        public virtual string In60Equipo
        {
            get;
            set;
        }
    
        public virtual string in60mm
        {
            get;
            set;
        }
    
        public virtual Nullable<double> In60CantidadSug
        {
            get;
            set;
        }
    
        public virtual string In60Observacion
        {
            get;
            set;
        }
    
        public virtual string in60Anaperiodos
        {
            get;
            set;
        }
    
        public virtual Nullable<int> in60AnaCantMeses
        {
            get;
            set;
        }
    
        public virtual Nullable<double> in60AnaConConsumo
        {
            get;
            set;
        }
    
        public virtual Nullable<double> in60AnaConPromedio
        {
            get;
            set;
        }
    
        public virtual string in60AnaConRotacion
        {
            get;
            set;
        }
    
        public virtual Nullable<double> in60AnaConDesvStandar
        {
            get;
            set;
        }
    
        public virtual Nullable<double> in60AnaConStock
        {
            get;
            set;
        }
    
        public virtual Nullable<double> in60AnaConNivelStock
        {
            get;
            set;
        }
    
        public virtual string in60AnaCantSugerida
        {
            get;
            set;
        }
    
        public virtual int In60Id
        {
            get;
            set;
        }

        #endregion
    }
}
