//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace MC.ControlPedido.Model
{
    public partial class Menu
    {
        #region Primitive Properties
    
        public virtual string Sistema
        {
            get;
            set;
        }
    
        public virtual string Opcion
        {
            get;
            set;
        }
    
        public virtual string Nivel
        {
            get;
            set;
        }
    
        public virtual string Nombre
        {
            get;
            set;
        }
    
        public virtual bool SubNivel
        {
            get;
            set;
        }
    
        public virtual string Ruta
        {
            get;
            set;
        }
    
        public virtual Nullable<int> IdMenu
        {
            get;
            set;
        }
    
        public virtual Nullable<int> MenuPadre
        {
            get;
            set;
        }
    
        public virtual string Ruta_1
        {
            get;
            set;
        }
    
        public virtual Nullable<int> IdMenu_1
        {
            get;
            set;
        }
    
        public virtual Nullable<int> MenuPadre_1
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Perfil> Perfil
        {
            get
            {
                if (_perfil == null)
                {
                    var newCollection = new FixupCollection<Perfil>();
                    newCollection.CollectionChanged += FixupPerfil;
                    _perfil = newCollection;
                }
                return _perfil;
            }
            set
            {
                if (!ReferenceEquals(_perfil, value))
                {
                    var previousValue = _perfil as FixupCollection<Perfil>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupPerfil;
                    }
                    _perfil = value;
                    var newValue = value as FixupCollection<Perfil>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupPerfil;
                    }
                }
            }
        }
        private ICollection<Perfil> _perfil;

        #endregion
        #region Association Fixup
    
        private void FixupPerfil(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Perfil item in e.NewItems)
                {
                    if (!item.Menu.Contains(this))
                    {
                        item.Menu.Add(this);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Perfil item in e.OldItems)
                {
                    if (item.Menu.Contains(this))
                    {
                        item.Menu.Remove(this);
                    }
                }
            }
        }

        #endregion
    }
}
